FROM node:14-alpine as build
WORKDIR /app

ARG OFFICE_BASE_URL
ARG USER_BASE_URL
ARG LEAVE_BASE_URL
ARG TIMESHEET_BASE_URL
ARG UTILITY_BASE_URL
ARG JOB_BASE_URL
ARG SUBSCRIPTION_BASE_URL
ARG HOLIDAY_BASE_URL
ARG CMS_BASE_URL
ARG PATIENT_SCHEDULING_BASE_URL
ARG CONTRACT_BASE_URL
ARG PERFORMANCE_REVIEW_BASE_URL
ARG REACT_APP_SCHEDULER_BASE_URL
ARG REACT_APP_NOTES_BASE_URL
ARG REACT_APP_TASK_MANAGEMENT_BASE_URL
ARG REACT_APP_NOTIFICATIONS_BASE_URL
ARG REACT_APP_TAX_MANAGEMENT_BASE_URL 
ARG REACT_APP_VENDOR_MANAGEMENT_BASE_URL 
ARG PROMOCODES_BASE_URL
ARG PERSONNEL_BASE_URL
ARG REACT_APP_SENTRY_URL

ARG AD_AUTHORITY_SUSI
ARG AD_AUTHORITY_PR
ARG AD_AUTHORITY_SU

ARG WEB_APP_CLIENT_ID
ARG AUTH_SCOPE

ARG STORAGE_ACCOUNT_NAME
ARG STORAGE_CONTAINER_NAME

ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_DATABASE_URL
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID
ARG FIREBASE_MEASUREMENT_ID
ARG FIREBASE_PUBLIC_KEY
ARG SUPPORT_HELPDESK_BASE_URL
ARG PROMOTION_BASE_URL





ARG SENDBIRD_APP_ID
ARG SENDBIRD_API_TOKEN
ARG SENDBIRD_REQUEST_URL
ARG STRIPE_LOGIN_URL
ARG CURRENT_ENV
ARG CUSTOMER_ORDER_BASE_URL





ARG STRIPE_SECRET_KEY
ARG GOOGLE_API_KEY
ARG PATIENT_ANDROID_APP_STORE_LINK
ARG PATIENT_IOS_APP_STORE_LINK


ENV REACT_APP_OFFICE_BASE_URL $OFFICE_BASE_URL
ENV REACT_APP_USER_BASE_URL $USER_BASE_URL
ENV REACT_APP_LEAVE_BASE_URL $LEAVE_BASE_URL
ENV REACT_APP_TIMESHEET_BASE_URL $TIMESHEET_BASE_URL
ENV REACT_APP_UTILITY_BASE_URL $UTILITY_BASE_URL
ENV REACT_APP_JOB_BASE_URL $JOB_BASE_URL     
ENV REACT_APP_SUBSCRIPTION_BASE_URL $SUBSCRIPTION_BASE_URL
ENV REACT_APP_HOLIDAY_BASE_URL $HOLIDAY_BASE_URL
ENV REACT_APP_CMS_BASE_URL $CMS_BASE_URL
ENV REACT_APP_PATIENT_SCHEDULING_BASE_URL $PATIENT_SCHEDULING_BASE_URL
ENV REACT_APP_CONTRACT_BASE_URL $CONTRACT_BASE_URL
ENV REACT_APP_PERFORMANCE_REVIEW_BASE_URL $PERFORMANCE_REVIEW_BASE_URL
ENV REACT_APP_SCHEDULER_BASE_URL $REACT_APP_SCHEDULER_BASE_URL
ENV REACT_APP_NOTES_BASE_URL $REACT_APP_NOTES_BASE_URL
ENV REACT_APP_TASK_MANAGEMENT_BASE_URL $REACT_APP_TASK_MANAGEMENT_BASE_URL
ENV REACT_APP_NOTIFICATIONS_BASE_URL $REACT_APP_NOTIFICATIONS_BASE_URL
ENV REACT_APP_TAX_MANAGEMENT_BASE_URL $REACT_APP_TAX_MANAGEMENT_BASE_URL 
ENV REACT_APP_VENDOR_MANAGEMENT_BASE_URL $REACT_APP_VENDOR_MANAGEMENT_BASE_URL
ENV REACT_APP_PROMOCODES_BASE_URL ${PROMOCODES_BASE_URL}
ENV REACT_APP_PERSONNEL_BASE_URL ${PERSONNEL_BASE_URL}
ENV REACT_APP_REACT_APP_SENTRY_URL ${REACT_APP_SENTRY_URL}

ENV REACT_APP_AZURE_AD_AUTHORITY $AD_AUTHORITY_SUSI
ENV REACT_APP_AZURE_AD_AUTHORITY_RESET $AD_AUTHORITY_PR
ENV REACT_APP_AZURE_AD_AUTHORITY_SIGNUP $AD_AUTHORITY_SU

ENV REACT_APP_AZURE_APP_CLIENT_ID $WEB_APP_CLIENT_ID
ENV REACT_APP_AZURE_APP_SCOPES $AUTH_SCOPE

ENV REACT_APP_AZURE_STORAGE_ACCOUNT $STORAGE_ACCOUNT_NAME
ENV REACT_APP_AZURE_STORAGE_CONTAINER $STORAGE_CONTAINER_NAME

ENV REACT_APP_FIREBASE_API_KEY $FIREBASE_API_KEY
ENV REACT_APP_FIREBASE_AUTH_DOMAIN $FIREBASE_AUTH_DOMAIN
ENV REACT_APP_FIREBASE_DATABASE_URL $FIREBASE_DATABASE_URL
ENV REACT_APP_FIREBASE_PROJECT_ID $FIREBASE_PROJECT_ID
ENV REACT_APP_FIREBASE_STORAGE_BUCKET $FIREBASE_STORAGE_BUCKET
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID $FIREBASE_MESSAGING_SENDER_ID
ENV REACT_APP_FIREBASE_APP_ID $FIREBASE_APP_ID
ENV REACT_APP_FIREBASE_MEASUREMENT_ID $FIREBASE_MEASUREMENT_ID
ENV REACT_APP_FIREBASE_PUBLIC_KEY $FIREBASE_PUBLIC_KEY
ENV REACT_APP_SUPPORT_HELPDESK_BASE_URL $SUPPORT_HELPDESK_BASE_URL
ENV REACT_APP_PROMOTION_BASE_URL $PROMOTION_BASE_URL





ENV REACT_APP_STRIPE_KEY $STRIPE_SECRET_KEY

ENV REACT_APP_GOOGLE_API_KEY $GOOGLE_API_KEY

ENV REACT_APP_PATIENT_ANDROID_APP_STORE_LINK $PATIENT_ANDROID_APP_STORE_LINK
ENV REACT_APP_PATIENT_IOS_APP_STORE_LINK $PATIENT_IOS_APP_STORE_LINK
ENV REACT_APP_SENDBIRD_APP_ID ${SENDBIRD_APP_ID}
ENV REACT_APP_SENDBIRD_API_TOKEN ${SENDBIRD_API_TOKEN}
ENV REACT_APP_SENDBIRD_REQUEST_URL ${SENDBIRD_REQUEST_URL}
ENV REACT_APP_STRIPE_LOGIN_URL ${STRIPE_LOGIN_URL}

ENV REACT_APP_CURRENT_ENV ${CURRENT_ENV}
ENV REACT_APP_CUSTOMER_ORDER_BASE_URL ${CUSTOMER_ORDER_BASE_URL}




ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
#RUN npm ci --silent
RUN npm install
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

WORKDIR /usr/share/nginx/html

CMD ["/bin/sh", "-c", "nginx -g \"daemon off;\""]