apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-ui
  name: web-ui
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  type: NodePort
  selector:
    io.kompose.service: web-ui
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-ui
    app: web-ui
  name: web-ui
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
        io.kompose.service: web-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web-ui
        app: web-ui
    spec:
      containers:                 
      - name: web-ui
        image: mxhhstagingcr.azurecr.io/webui:IMAGE_VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources: {}
      restartPolicy: Always
status: {}
